name: pull_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'GitHubAction:')"

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          #cache: gradle

      - name: Modify permission and Build
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/hhhaiai/analysys-dev-sdk.git
          echo "===========clone over===================="
          ls
          cd analysys-dev-sdk
          echo "===========into analysys-dev-sdk===================="
          ls
          git checkout dev
          bash syncSubmodule.sh
          chmod -R 777 *
          git config core.filemode false
          # install tools
          sudo apt-get update
          sudo apt-get -y install unzip
          ./gradlew build

      # general file list
      # ./dev-sdk-debug.jar  ./dev-sdk-release.jar  
      # ./casedemo-debug.apk ./updatecase-debug.apk ./appdemo-debug.apk
      # ./tree.txt
      - name: prepare source
        shell: bash
        continue-on-error: true
        run: |
          cp ./analysys-dev-sdk/dev-sdk/build/outputs/aar/dev-sdk-debug.aar ./dev-sdk-debug.aar
          cp ./analysys-dev-sdk/dev-sdk/build/outputs/aar/dev-sdk-release.aar ./dev-sdk-release.aar
          cp ./analysys-dev-sdk/casedemo/build/outputs/apk/debug/casedemo-debug.apk ./casedemo-debug.apk
          cp ./analysys-dev-sdk/appdemo/build/outputs/apk/debug/appdemo-debug.apk ./appdemo-debug.apk
          cp ./analysys-dev-sdk/updatecase/build/outputs/apk/debug/updatecase-debug.apk ./updatecase-debug.apk
          ls -R *>./tree.txt
          echo "${{github.repository_owner}} will upload files"
          #######################################################################################################
          ######################################## upload files #################################################
          #######################################################################################################
          file_name=tree.txt

      #     wget  https://github.com/hhhaiai/uploadGithub/releases/download/v1.1/uploadGithubService-1.1-jar-with-dependencies.jar
      #     dat=$(date "+%H%M%S")
      #     tpn=${{ github.repository }}
      #     pn=`echo $tpn | cut -d \/ -f 2`
      #     us=${{github.repository_owner}}
      #     echo "project name: $pn"
      #     today=$(date "+%Y%m%d")
      #     upload_file_name="ci/$today/${dat}-$pn-${file_name}"
      #     chmod -R 777 *
      #     echo "=================文件查看===================="
      #     ls
      #     echo "==dat== $dat"
      #     echo "==dat== $upload_file_name"
      #     # https://docs.github.com/cn/actions/learn-github-actions/contexts#github-context
      #     echo "===========================">>${file_name}
      #     echo "Project: ${{ github.repository }}">>${file_name}
      #     echo "Job:  ${{ github.job }}">>${file_name}
      #     echo "Build commit sha:  ${{ github.sha }}">>${file_name}
      #     echo "job.container.id:  ${{ job.container.id }}">>${file_name}
      #     echo "job.container.network:  ${{ job.container.network }}">>${file_name}
      #     java -jar uploadGithubService-1.1-jar-with-dependencies.jar  -owner hhhaiai -repo Git_result -target-dir-full-name  $upload_file_name -native-file ${file_name}  -token ${{ secrets.GTOKEN }} -commit-messge  "GitHubAction: Build commit ${{ github.sha }}. Project: ${{ github.repository }} Job ${{ github.job }}, created by ${{ github.workflow }} " -commit-auther "UploadGithubService" -commit-email "sanbo.xyz@gmail.com"

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          #server_address: smtp.gmail.com
          #server_port: 465
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: GithubActions( ${{ github.job }} ) - ${{ github.sha }}
          to: ${{ secrets.MAIL_LIST }}
          from: github.com/hhhaiai
          body: Build job ( ${{ github.job }} ) of ${{ github.repository }} completed successfully!
          ignore_cert: true
          priority: low
          secure: true
          attachments: ./tree.txt, ./dev-sdk-debug.aar, ./dev-sdk-release.aar, ./casedemo-debug.apk, ./updatecase-debug.apk, ./appdemo-debug.apk
          #html_body: file://dev-sdk/build/reports/lint-results.html
          #convert_markdown: true