name: ut_x86_64-google_apis_playstore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule:
  #   - cron: '0 */3 * * *'  #   分 时 日 月 周

jobs:
  build:
    runs-on: macOS-11
    if: "!startsWith(github.event.head_commit.message, 'GitHubAction:')"
    strategy:
      matrix:
        api-level: [ 28, 29, 31 ]
        target: [google_apis_playstore]
        arch: [x86_64]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          #cache: gradle
      
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-cache

      - name: checkout analysys-dev-sdk and sync
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/hhhaiai/analysys-dev-sdk.git
          echo "===========clone over===================="
          ls
          cd analysys-dev-sdk
          echo "===========into analysys-dev-sdk===================="
          ls
          git checkout dev
          bash syncSubmodule.sh
          chmod -R 777 *
          git config core.filemode false

      - name: copy and chmod
        shell: bash
        continue-on-error: true
        run: |
          chmod -R 777 *
          bash copy.sh
          chmod -R 777 *
          echo "===============拷贝完成=================="
          ls

      - name: run UT tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level_x86_default }}
          target: ${{ matrix.target_x86_default }}
          arch: ${{ matrix.arch_x86_default }}
          profile: Nexus 6
          # cores: 4
          # ram-size: 4096M
          # sdcard-path-or-size: 1000M
          avd-name: ${{ matrix.api-level_x86_default }}-${{ matrix.target_x86_default }}-${{ matrix.arch_x86_default }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            echo "=================查看当前目录============="
            ls
            if [ "$(uname -s)" = "Darwin" ]; then
              sed -i '' "s/apply\ plugin:\ 'analysys_dev_track_tool'/\/\/apply\ plugin:\ 'analysys_dev_track_tool'/g" dev-sdk/build.gradle
              sed -i '' "s/def\ isRelease\ =\ true/def\ isRelease\ =\ false/g" dev-sdk/build.gradle
              sed -i '' "s/androidTestImplementation\ 'com.umeng.umsdk:common:9.4.4'/implementation\ 'com.umeng.umsdk:common:9.4.4'/g" dev-sdk/build.gradle
              sed -i '' "s/androidTestImplementation\ 'com.umeng.umsdk:asms:1.4.1'/implementation\ 'com.umeng.umsdk:asms:1.4.1'/g" dev-sdk/build.gradle
              sed -i '' "s/androidTestImplementation\ 'com.umeng.umsdk:apm:1.5.2'/implementation\ 'com.umeng.umsdk:apm:1.5.2'/g" dev-sdk/build.gradle
              sed -i '' "s/androidTestImplementation\ 'com.umeng.umsdk:abtest:1.0.0'/implementation\ 'com.umeng.umsdk:abtest:1.0.0'/g" dev-sdk/build.gradle
              sed -i '' "s/androidTestImplementation\ 'com.tencent.bugly:crashreport:3.3.92'/implementation\ 'com.tencent.bugly:crashreport:3.3.92'/g" dev-sdk/build.gradle
            else
              sed -i "s/apply\ plugin:\ 'analysys_dev_track_tool'/\/\/apply\ plugin:\ 'analysys_dev_track_tool'/g" dev-sdk/build.gradle
              sed -i "s/def\ isRelease\ =\ true/def\ isRelease\ =\ false/g" dev-sdk/build.gradle
              sed -i "s/androidTestImplementation\ 'com.umeng.umsdk:common:9.4.4'/implementation\ 'com.umeng.umsdk:common:9.4.4'/g" dev-sdk/build.gradle
              sed -i "s/androidTestImplementation\ 'com.umeng.umsdk:asms:1.4.1'/implementation\ 'com.umeng.umsdk:asms:1.4.1'/g" dev-sdk/build.gradle
              sed -i "s/androidTestImplementation\ 'com.umeng.umsdk:apm:1.5.2'/implementation\ 'com.umeng.umsdk:apm:1.5.2'/g" dev-sdk/build.gradle
              sed -i "s/androidTestImplementation\ 'com.umeng.umsdk:abtest:1.0.0'/implementation\ 'com.umeng.umsdk:abtest:1.0.0'/g" dev-sdk/build.gradle
              sed -i "s/androidTestImplementation\ 'com.tencent.bugly:crashreport:3.3.92'/implementation\ 'com.tencent.bugly:crashreport:3.3.92'/g" dev-sdk/build.gradle
            fi
            ./gradlew connectedAndroidTest mergeAndroidReports || true
            echo "==============run case over==============="
            tar -zcvf ut_${{ matrix.api-level_x86_default }}-${{ matrix.target_x86_default }}-${{ matrix.arch_x86_default }}.tgz build/ dev-sdk/build/reports/>t.txt || true
            echo "==============tar ut over. ls==============="
            echo "${{ matrix.api-level_x86_default }}-${{ matrix.target_x86_default }}-${{ matrix.arch_x86_default }} 运行完毕。。。。。。。。。"
            rm -rf ~/.android/avd/

      - name: ypload
        shell: bash
        continue-on-error: true
        run: |
            echo "${{github.repository_owner}} will upload files"
            #######################################################################################################
            ######################################## upload files #################################################
            #######################################################################################################
            file_name=ut_${{ matrix.api-level_x86_default }}-${{ matrix.target_x86_default }}-${{ matrix.arch_x86_default }}.tgz
            wget  https://github.com/hhhaiai/uploadGithub/releases/download/v1.1/uploadGithubService-1.1-jar-with-dependencies.jar
            dat=$(date "+%H%M%S")
            tpn=${{ github.repository }}
            pn=`echo $tpn | cut -d \/ -f 2`
            us=${{github.repository_owner}}
            # echo "project name: ${pn}"
            today=$(date "+%Y%m%d")
            upload_file_name="ci/$today/${pn}_${dat}_${file_name}"
            chmod -R 777 *
            echo "=================下载完成文件查看===================="
            ls
            # https://docs.github.com/cn/actions/learn-github-actions/contexts#github-context
            echo "dat: $dat">>${file_name}
            echo "upload_file_name:  $upload_file_name">>${file_name}
            echo "Project: ${{ github.repository }}">>${file_name}
            echo "Job:  ${{ github.job }}">>${file_name}
            echo "Build commit sha:  ${{ github.sha }}">>${file_name}
            echo "job.container.id:  ${{ job.container.id }}">>${file_name}
            echo "job.container.network:  ${{ job.container.network }}">>${file_name}
            echo "===========================">>${file_name}
            java -jar uploadGithubService-1.1-jar-with-dependencies.jar  -owner hhhaiai -repo Git_result -target-dir-full-name  $upload_file_name -native-file ${file_name}  -token ${{ secrets.GTOKEN }} -commit-messge  "GitHubAction: UT ${{ github.repository }} Job ${{ github.job }}, created by ${{ github.workflow }} " -commit-auther "GitHubAction" -commit-email "sanbo.xyz@gmail.com"


